-- Digest tables for daily AI-generated valuation digests
-- Design doc: AI Signal + Daily Digest for TSLA Conversion

-- ─── Digests table ──────────────────────────────────────────────────────────
-- One row per day. Generated by the generate-daily-digest cron job.
-- Content is generated once per language (not per user).

CREATE TABLE IF NOT EXISTS digests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL UNIQUE,
  zone TEXT NOT NULL,                    -- BARGAIN/CHEAP/FAIR/EXPENSIVE/OVERPRICED
  zone_changed BOOLEAN NOT NULL DEFAULT false,
  ps_ratio NUMERIC NOT NULL,
  price NUMERIC NOT NULL,
  market_cap NUMERIC,
  revenue_ttm NUMERIC,
  is_stale_data BOOLEAN NOT NULL DEFAULT false,
  content_zh TEXT,
  content_en TEXT,
  content_es TEXT,
  content_ja TEXT,
  content_ko TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fetching recent digests (frontend feed)
CREATE INDEX IF NOT EXISTS idx_digests_date ON digests (date DESC);

-- ─── User preferences table ────────────────────────────────────────────────
-- Stores email delivery preferences for Pro subscribers.
-- user_id references Supabase Auth users.

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  email_confirmed_at TIMESTAMPTZ,
  language TEXT NOT NULL DEFAULT 'zh',
  alert_on_zone_change BOOLEAN NOT NULL DEFAULT true,
  digest_frequency TEXT NOT NULL DEFAULT 'daily',  -- 'daily' | 'weekly' | 'none'
  stripe_customer_id TEXT,
  unsubscribed_at TIMESTAMPTZ,
  hard_bounce_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for email sending: find active Pro users who want digests
CREATE INDEX IF NOT EXISTS idx_user_prefs_digest
  ON user_preferences (digest_frequency, email)
  WHERE unsubscribed_at IS NULL
    AND hard_bounce_at IS NULL
    AND email_confirmed_at IS NOT NULL;
